import "server-only";

import { and, asc, desc, eq } from "drizzle-orm";
import { unstable_cache } from "next/cache";

import { db } from "@/db";
import {
  githubRepositories,
  hackathons,
  projectRepositories,
  projects,
  repositoryCommits,
  repositoryDependencies,
  repositoryFiles,
} from "@/db/schema";
import { getProjectBySlug, type ProjectDetail } from "@/lib/data/projects";
import { getProjectEvidence } from "@/lib/data/project-evidence";
import { getProjectTeamStats } from "@/lib/data/project-team";
import { createGithubClient } from "@/lib/github/client";
import { getGithubReadme } from "@/lib/github/readme-cache";

import {
  buildDevpostSection,
  buildEvidenceSection,
  IGNORED_PATH_PATTERNS,
} from "./project-context";

/*
 * Budgets. The export is meant to be pasted into an AI chat, so the whole
 * document targets roughly 60K characters (~15K tokens): small enough to be
 * cheap and fast, large enough that the agent sees real code. Every cap below
 * exists to protect that target — raise them deliberately, not casually.
 */
const README_CHAR_CAP = 8_000;
const MAX_TREE_PATHS = 120;
const MAX_COMMITS = 20;
const MAX_DEPENDENCY_LINES = 40;
/** Shared budget for fetched file contents (source + extra docs). */
const SOURCE_CHAR_BUDGET = 36_000;
const MAX_SOURCE_FILES = 10;
const PER_FILE_CHAR_CAP = 6_000;
const MAX_DOC_FILES = 2;
const PER_DOC_CHAR_CAP = 3_000;
/** Files larger than this are never fetched — they would blow the budget anyway. */
const MAX_CANDIDATE_BYTES = 48_000;

const MANIFEST_NAMES = new Set([
  "package.json",
  "pyproject.toml",
  "requirements.txt",
  "go.mod",
  "cargo.toml",
  "gemfile",
  "composer.json",
  "dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
]);

const ENTRY_POINT_PATTERN =
  /(^|\/)(index|main|app|server|cli)\.(ts|tsx|js|jsx|mjs|py|go|rs|rb|java)$/i;
const NEXT_APP_PATTERN = /(^|\/)app\/.*(page|layout|route)\.(ts|tsx|js|jsx)$/;
const DOC_PATTERN = /\.(md|mdx)$/i;
const README_PATTERN = /(^|\/)readme\.[a-z]+$/i;

type FileCandidate = {
  path: string;
  blobSha: string;
  language: string | null;
  sizeBytes: number;
  isDoc: boolean;
  score: number;
};

type RepoCoordinates = { owner: string; name: string };

/**
 * Compact, self-contained markdown bundle for chatting with an external AI
 * agent about one project. Returns null when the project does not exist.
 *
 * Unlike `assembleProjectContext` (tuned for in-app prompts), this fetches a
 * budgeted selection of real source files from GitHub, so it is cached: the
 * repository index only changes on re-ingestion, and blob fetches are the
 * expensive part.
 */
export const assembleProjectExport = unstable_cache(
  assembleProjectExportUncached,
  ["project-export"],
  { revalidate: 1800 },
);

async function assembleProjectExportUncached(
  hackathonSlug: string,
  projectSlug: string,
): Promise<string | null> {
  const project = await getProjectBySlug(hackathonSlug, projectSlug);
  if (!project) return null;

  const [readme, evidence, teamSection, repoIndex] = await Promise.all([
    getGithubReadme(project.githubUrl),
    getProjectEvidence(hackathonSlug, projectSlug).then(buildEvidenceSection),
    getProjectTeamStats(hackathonSlug, projectSlug).then(buildTeamLine),
    loadRepositoryIndex(hackathonSlug, projectSlug),
  ]);

  const sourceSection = repoIndex
    ? await buildSourceFilesSection(repoIndex.repo, repoIndex.candidates)
    : "## Key source files\n\nNo repository index available; no source files included.";

  return [
    `# Project export: ${project.name}`,
    "This document was generated by HackStack to give an AI agent context about a hackathon project. Sections are labeled with their provenance; content marked as truncated was cut to keep this document small.",
    buildMetadataSection(project, teamSection),
    buildDevpostSection(project),
    buildReadmeSection(readme?.content ?? null),
    evidence,
    repoIndex
      ? buildStructureSection(repoIndex.paths, repoIndex.deps, repoIndex.commits)
      : "## Codebase structure\n\nNo repository index available.",
    sourceSection,
  ].join("\n\n");
}

// ── Metadata ────────────────────────────────────────────────────

function buildMetadataSection(project: ProjectDetail, teamLine: string): string {
  const lines = [
    `- Hackathon: ${project.hackathonName}`,
    project.tagline ? `- Tagline: ${project.tagline}` : null,
    `- Devpost: ${project.devpostUrl}`,
    project.githubUrl ? `- GitHub: ${project.githubUrl}` : "- GitHub: not linked",
    project.demoUrl ? `- Demo: ${project.demoUrl}` : null,
    project.videoUrl ? `- Video: ${project.videoUrl}` : null,
    project.isWinner
      ? `- Result: winner${project.winningTrack ? ` (${project.winningTrack})` : ""}`
      : null,
    teamLine,
  ].filter(Boolean);

  return `## Project metadata\n\n${lines.join("\n")}`;
}

async function buildTeamLine(
  stats: Awaited<ReturnType<typeof getProjectTeamStats>>,
): Promise<string> {
  if (stats.state !== "ready") return "- Team: contributor stats unavailable";
  const contributors = stats.contributors
    .map((c) => `${c.displayName || c.githubLogin} (${c.creditedCommitCount} commits)`)
    .join(", ");
  return `- Team: ${stats.contributors.length} GitHub contributor(s) — ${contributors}`;
}

// ── README ──────────────────────────────────────────────────────

function buildReadmeSection(content: string | null): string {
  const header = "## README (from the GitHub repository)";
  if (!content?.trim()) return `${header}\n\nNo README available.`;
  const truncated =
    content.length > README_CHAR_CAP
      ? content.slice(0, README_CHAR_CAP) + "\n\n[README truncated for size]"
      : content;
  return `${header}\n\n${truncated}`;
}

// ── Repository index (one round of queries, shared by two sections) ──

async function loadRepositoryIndex(hackathonSlug: string, projectSlug: string) {
  const [row] = await db
    .select({
      projectId: projects.id,
      repoOwner: githubRepositories.ownerLogin,
      repoName: githubRepositories.name,
    })
    .from(projects)
    .innerJoin(hackathons, eq(projects.hackathonId, hackathons.id))
    .innerJoin(projectRepositories, eq(projectRepositories.projectId, projects.id))
    .innerJoin(
      githubRepositories,
      eq(projectRepositories.repositoryId, githubRepositories.id),
    )
    .where(
      and(
        eq(hackathons.devpostSlug, hackathonSlug),
        eq(projects.devpostSlug, projectSlug),
      ),
    )
    .limit(1);

  if (!row) return null;

  const projectFilter = eq(projectRepositories.projectId, row.projectId);

  const [files, deps, commits] = await Promise.all([
    db
      .select({
        path: repositoryFiles.path,
        blobSha: repositoryFiles.blobSha,
        language: repositoryFiles.language,
        sizeBytes: repositoryFiles.sizeBytes,
      })
      .from(repositoryFiles)
      .innerJoin(
        projectRepositories,
        eq(repositoryFiles.projectRepositoryId, projectRepositories.id),
      )
      .where(and(projectFilter, eq(repositoryFiles.isBinary, false)))
      .orderBy(asc(repositoryFiles.path)),
    db
      .select({
        packageName: repositoryDependencies.packageName,
        versionConstraint: repositoryDependencies.versionConstraint,
        manifestPath: repositoryDependencies.manifestPath,
      })
      .from(repositoryDependencies)
      .innerJoin(
        projectRepositories,
        eq(repositoryDependencies.projectRepositoryId, projectRepositories.id),
      )
      .where(projectFilter)
      .orderBy(
        asc(repositoryDependencies.manifestPath),
        asc(repositoryDependencies.packageName),
      ),
    db
      .select({ message: repositoryCommits.message })
      .from(repositoryCommits)
      .innerJoin(
        projectRepositories,
        eq(repositoryCommits.projectRepositoryId, projectRepositories.id),
      )
      .where(projectFilter)
      .orderBy(desc(repositoryCommits.authoredAt))
      .limit(MAX_COMMITS),
  ]);

  const usable = files.filter(
    (f) => !IGNORED_PATH_PATTERNS.some((re) => re.test(f.path)),
  );

  return {
    repo: { owner: row.repoOwner, name: row.repoName } satisfies RepoCoordinates,
    paths: usable.map((f) => f.path),
    deps,
    commits,
    candidates: rankFileCandidates(usable),
  };
}

// ── Structure (tree, deps, commits — tighter caps than the chat context) ──

function buildStructureSection(
  paths: string[],
  deps: Array<{
    packageName: string;
    versionConstraint: string | null;
    manifestPath: string;
  }>,
  commits: Array<{ message: string }>,
): string {
  const parts = ["## Codebase structure (from repository index)"];

  const shown = paths.slice(0, MAX_TREE_PATHS);
  if (shown.length === 0) {
    parts.push("### Files\n\nNo file index available.");
  } else {
    const suffix =
      paths.length > shown.length
        ? `\n[${paths.length - shown.length} more files omitted for size]`
        : "";
    parts.push(
      `### Files (${shown.length} of ${paths.length})\n\n\`\`\`\n${shown.join("\n")}${suffix}\n\`\`\``,
    );
  }

  if (deps.length === 0) {
    parts.push("### Dependencies\n\nNo dependency index available.");
  } else {
    const byManifest = new Map<string, string[]>();
    for (const d of deps) {
      const entry = `${d.packageName}${d.versionConstraint ? `@${d.versionConstraint}` : ""}`;
      byManifest.set(d.manifestPath, [...(byManifest.get(d.manifestPath) ?? []), entry]);
    }
    const lines = [...byManifest.entries()].map(
      ([m, list]) => `- ${m}: ${list.join(", ")}`,
    );
    const shownLines = lines.slice(0, MAX_DEPENDENCY_LINES);
    if (lines.length > shownLines.length) {
      shownLines.push(`[${lines.length - shownLines.length} more manifests omitted]`);
    }
    parts.push(`### Dependencies\n\n${shownLines.join("\n")}`);
  }

  if (commits.length === 0) {
    parts.push("### Recent commits\n\nNo commit history available.");
  } else {
    const lines = commits.map((c) => `- ${c.message.split("\n")[0].trim()}`);
    parts.push(`### Recent commits (newest first)\n\n${lines.join("\n")}`);
  }

  return parts.join("\n\n");
}

// ── Source file selection and fetching ──────────────────────────

/**
 * Ranks indexed files by how much they explain the project: extra docs and
 * dependency manifests first, then entry points and routes, then remaining
 * source files preferring shallow paths and small sizes. The README is
 * excluded (it has its own section).
 */
function rankFileCandidates(
  files: Array<{
    path: string;
    blobSha: string;
    language: string | null;
    sizeBytes: number;
  }>,
): FileCandidate[] {
  const candidates: FileCandidate[] = [];

  for (const file of files) {
    if (file.sizeBytes === 0 || file.sizeBytes > MAX_CANDIDATE_BYTES) continue;
    if (README_PATTERN.test(file.path)) continue;

    const baseName = file.path.split("/").pop()?.toLowerCase() ?? "";
    const depth = file.path.split("/").length;
    const isDoc = DOC_PATTERN.test(file.path);

    let score: number;
    if (isDoc) {
      score = 500;
    } else if (MANIFEST_NAMES.has(baseName)) {
      score = 400;
    } else if (ENTRY_POINT_PATTERN.test(file.path) || NEXT_APP_PATTERN.test(file.path)) {
      score = 300;
    } else if (file.language) {
      score = 100;
    } else {
      continue; // unrecognized non-doc file: config noise, lockfile leftovers, etc.
    }

    // Shallow files explain more than deeply nested ones; small files cost less.
    score -= depth * 10 + file.sizeBytes / 2048;

    candidates.push({ ...file, isDoc, score });
  }

  return candidates.sort((a, b) => b.score - a.score);
}

async function buildSourceFilesSection(
  repo: RepoCoordinates,
  candidates: FileCandidate[],
): Promise<string> {
  const header = "## Key source files (fetched from GitHub, selected and truncated for size)";
  if (candidates.length === 0) return `${header}\n\nNo suitable source files found.`;

  let client;
  try {
    client = createGithubClient();
  } catch {
    return `${header}\n\nSource contents unavailable (GitHub access is not configured).`;
  }

  // Greedy selection under the shared character budget.
  const selected: FileCandidate[] = [];
  let docCount = 0;
  let budget = SOURCE_CHAR_BUDGET;
  for (const candidate of candidates) {
    if (selected.length >= MAX_SOURCE_FILES) break;
    if (candidate.isDoc && docCount >= MAX_DOC_FILES) continue;
    const cap = candidate.isDoc ? PER_DOC_CHAR_CAP : PER_FILE_CHAR_CAP;
    const cost = Math.min(candidate.sizeBytes, cap);
    if (cost > budget) continue;
    budget -= cost;
    if (candidate.isDoc) docCount += 1;
    selected.push(candidate);
  }

  const results = await Promise.allSettled(
    selected.map(async (file) => {
      const response = await client.rest.git.getBlob({
        owner: repo.owner,
        repo: repo.name,
        file_sha: file.blobSha,
      });
      if (response.data.encoding !== "base64") {
        throw new Error(`unsupported blob encoding ${response.data.encoding}`);
      }
      const content = Buffer.from(
        response.data.content.replaceAll("\n", ""),
        "base64",
      ).toString("utf8");
      return { file, content };
    }),
  );

  const parts = [header];
  let fetched = 0;
  for (const result of results) {
    if (result.status === "rejected") continue;
    const { file, content } = result.value;
    const cap = file.isDoc ? PER_DOC_CHAR_CAP : PER_FILE_CHAR_CAP;
    const truncated =
      content.length > cap
        ? content.slice(0, cap) + `\n[truncated — ${content.length - cap} more characters]`
        : content;
    const fence = file.language?.toLowerCase() ?? "";
    parts.push(`### ${file.path}\n\n\`\`\`${fence}\n${truncated}\n\`\`\``);
    fetched += 1;
  }

  if (fetched === 0) {
    parts.push("Source contents could not be fetched from GitHub right now.");
  }

  const omitted = candidates.length - fetched;
  if (omitted > 0) {
    parts.push(
      `[${omitted} more indexed source files omitted to keep this export small. The full file list is in the Codebase structure section above.]`,
    );
  }

  return parts.join("\n\n");
}
